In [1]:
import numpy as np

## numpy arrays

In [2]:
liste = [20,30,40]

In [3]:
type(liste)

list

In [4]:
np.array(liste)

array([20, 30, 40])

In [5]:
matrixList=[[10,20,30],[20,30,40],[50,60,70]]

In [6]:
matrixList[1][0]

20

In [7]:
matrixList[1]

[20, 30, 40]

In [8]:
np.array(matrixList)

array([[10, 20, 30],
       [20, 30, 40],
       [50, 60, 70]])

## arange

In [9]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

## zeros

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## linspace

In [17]:
np.linspace(0,20,6)   #belirtilen numaralar arasında, eşit olarak aralık bırakılmış şekilde dizi oluşturur.

array([ 0.,  4.,  8., 12., 16., 20.])

In [18]:
np.linspace(0,100,50)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

## eye

In [19]:
np.eye(3) #identity matrix oluşturmak için kullanılır

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## random

In [22]:
np.random.randn(5)  #randn nummpy dizisi dönderir

array([ 0.08571693, -1.33967101, -0.91964438, -1.84464935,  0.57097945])

In [23]:
np.random.randn(4,4)

array([[-0.91799928, -0.30103164,  0.72600003,  0.59009926],
       [ 1.54103927,  0.64831791, -0.82813916,  0.81842844],
       [ 0.76152012, -0.56691629,  0.70047365, -0.61352816],
       [-1.02357512,  0.59404908, -0.9971111 ,  0.51176027]])

In [25]:
np.random.randint(1,10) #1 ile 10 arası randon bir sayı üretir 10 dahil olmaz.

5

In [27]:
np.random.randint(1,300,5)

array([177,  43, 280, 157, 111])

In [28]:
numpyDizi = np.arange(30)

In [29]:
numpyDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [32]:
randomDizi = np.random.randint(0,100,20)

In [33]:
randomDizi

array([ 9,  9, 43, 33, 42, 50, 25,  9, 16, 62, 33, 71, 92, 55, 20, 30, 34,
        7, 62,  0])

## numpy dizi methodları

In [35]:
numpyDizi.reshape(5,6)  #30 eleman olduğu için 5x6 lık matrix oluşturur.

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [37]:
numpyDizi.max()

29

In [41]:
randomDizi.max()  #dizidek max değeri verir

92

In [42]:
randomDizi.min()

0

In [43]:
randomDizi.argmax()  #max olan değerin indexini verir

12

In [44]:
randomDizi.argmin()

19

In [46]:
numpyDizi.shape

(30,)

In [47]:
reshapeDizi = numpyDizi.reshape(5,6) 

In [48]:
reshapeDizi.shape

(5, 6)

In [49]:
reshapeDizi

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])