In [1]:
import numpy as np

In [2]:
myArray =np.arange(0,15)

In [3]:
myArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
myArray[5]

5

In [5]:
myArray[3:5]

array([3, 4])

In [6]:
myArray[3:8] = -5

In [7]:
myArray

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [8]:
baskaDizi = np.arange(0,24)

In [9]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [10]:
slicingDizisi = baskaDizi[4:9]

In [11]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [12]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [13]:
slicingDizisi[:] = 700

In [14]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [15]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [16]:
ornekDizi = np.arange(0,24)

In [17]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [18]:
ornekDiziKopyasi = ornekDizi.copy()

In [19]:
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [20]:
ornekDiziKopyasiSlicing =ornekDiziKopyasi[3:6]

In [23]:
ornekDiziKopyasiSlicing[:] = 777

In [24]:
ornekDiziKopyasiSlicing

array([777, 777, 777])

In [25]:
ornekDiziKopyasi

array([  0,   1,   2, 777, 777, 777,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [26]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## matrix

In [27]:
myList =[[10,20,30],[20,30,40],[50,60,70]]

In [28]:
matrixDizi = np.array(myList)

In [29]:
matrixDizi

array([[10, 20, 30],
       [20, 30, 40],
       [50, 60, 70]])

In [30]:
matrixDizi[1][2]

40

In [31]:
matrixDizi[1,2]

40

In [34]:
matrixDizi[0:2]

array([[10, 20, 30],
       [20, 30, 40]])

In [35]:
matrixDizi[0:,2]

array([30, 40, 70])

In [36]:
yeniListe = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [38]:
yeniMatrix = np.array(yeniListe)

In [39]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [40]:
yeniMatrix[[4,2,0]]

array([[20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

## operasyonlar

In [46]:
yeniBirDizi = np.random.randint(1,100,20)

In [47]:
yeniBirDizi

array([43,  7,  6, 20, 73, 27, 85, 98, 40, 36, 81,  6, 25, 97, 22, 44,  4,
       87, 27, 86])

In [48]:
sonucDizisi = yeniBirDizi > 24

In [49]:
sonucDizisi

array([ True, False, False, False,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True, False,  True, False,  True,
        True,  True])

In [50]:
yeniBirDizi[sonucDizisi]

array([43, 73, 27, 85, 98, 40, 36, 81, 25, 97, 44, 87, 27, 86])

In [51]:
yeniBirDizi[yeniBirDizi>24]

array([43, 73, 27, 85, 98, 40, 36, 81, 25, 97, 44, 87, 27, 86])

In [52]:
yeniBirDizi[yeniBirDizi<24]

array([ 7,  6, 20,  6, 22,  4])

In [53]:
sonDizi = np.arange(0,24)

In [54]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [55]:
sonDizi +sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [56]:
sonDizi*sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [57]:
sonDizi-sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [58]:
sonDizi/sonDizi

C:\Users\Gaye\AppData\Local\Temp\ipykernel_26752\1954055075.py:1: RuntimeWarning: invalid value encountered in divide
  sonDizi/sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [59]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [60]:
np.max(sonDizi)

23

In [61]:
np.min(sonDizi)

0